# Generated by Django 5.2 on 2025-04-18 17:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_service', '0005_alter_course_status'),
        ('lesson_service', '0004_alter_sectionitem_content_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionarySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название раздела')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='dict_section_banners/', verbose_name='Баннер раздела (необязательно)')),
                ('is_primary', models.BooleanField(default=False, help_text='Только один раздел может быть основным для курса.', verbose_name='Основной раздел курса')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_sections', to='course_service.course', verbose_name='Курс')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dictionary_sections', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан')),
            ],
            options={
                'verbose_name': 'Раздел словаря',
                'verbose_name_plural': 'Разделы словаря',
                'ordering': ['course', '-is_primary', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=200, verbose_name='Слово/Термин/Кандзи')),
                ('reading', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Чтение (хирагана/катакана)')),
                ('translation', models.TextField(blank=True, null=True, verbose_name='Перевод/Значение')),
                ('pronunciation_audio', models.FileField(blank=True, null=True, upload_to='dict_pronunciations/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])], verbose_name='Аудио произношения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dictionary_entries', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dictionary_entries', to='lesson_service.lesson', verbose_name='Урок (необязательно)')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='dict_service.dictionarysection', verbose_name='Раздел словаря')),
            ],
            options={
                'verbose_name': 'Словарная запись',
                'verbose_name_plural': 'Словарные записи',
                'ordering': ['section', 'term', 'reading'],
            },
        ),
        migrations.CreateModel(
            name='UserLearnedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изучения')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_by_users', to='dict_service.dictionaryentry', verbose_name='Словарная запись')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_dictionary_entries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Изученная запись',
                'verbose_name_plural': 'Изученные записи',
                'ordering': ['user', '-learned_at'],
                'unique_together': {('user', 'entry')},
            },
        ),
    ]
