# Generated by Django 5.1.7 on 2026-02-11 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanjiCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(db_index=True, max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KanjiStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compounds', to='dict_service.kanjicharacter')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='dict_service.kanjicharacter')),
            ],
            options={
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
