# Generated by Django 5.1.7 on 2026-02-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict_service', '0002_kanjicharacter_kanjistructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanjicharacter',
            name='decomposition_tree',
            field=models.JSONField(blank=True, default=dict, verbose_name='Дерево декомпозиции'),
        ),
    ]
