# Generated by Django 5.1.7 on 2026-02-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict_service', '0003_kanjicharacter_decomposition_tree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanjicharacter',
            name='character',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
