# Generated by Django 5.2 on 2025-04-02 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_featured',
        ),
    ]
