# Generated by Django 5.2 on 2025-04-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_service', '0002_remove_course_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subtitle',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'Архив'), ('free', 'Бесплатно')], default='draft', max_length=20),
        ),
    ]
