# Generated by Django 5.2 on 2025-04-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_service', '0003_course_subtitle_alter_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subtitle',
            field=models.CharField(max_length=255),
        ),
    ]
