# Generated by Django 5.2 on 2025-04-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_service', '0004_alter_course_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('free', 'Бесплатно')], default='draft', max_length=20),
        ),
    ]
