# Generated by Django 5.1.7 on 2026-02-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_service', '0005_alter_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('free', 'Бесплатно'), ('individual', 'Индивидуальный')], default='draft', max_length=20),
        ),
    ]
