# Generated by Django 5.2 on 2025-04-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='show_learned_items',
            field=models.BooleanField(default=True),
        ),
    ]
