# Generated by Django 5.1.7 on 2026-02-16 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_service', '0002_bonus_frame_image'),
        ('user_service', '0002_usersettings_show_learned_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_avatar_frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_with_active_frame', to='bonus_service.bonus'),
        ),
    ]
