# Generated by Django 5.1.7 on 2025-03-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationcode',
            name='target_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
