# Generated by Django 5.1.7 on 2026-01-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('achievement', 'Достижение'), ('system', 'Системное'), ('course', 'Курс'), ('streak', 'Серия дней'), ('level_up', 'Новый уровень')], default='system', max_length=20, verbose_name='Тип уведомления'),
        ),
    ]
