# Generated by Django 5.2 on 2025-04-17 17:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lesson_service', '0004_alter_sectionitem_content_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (необязательно)')),
                ('audio_file', models.FileField(upload_to='material_audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])], verbose_name='Аудио файл')),
                ('transcript', models.TextField(blank=True, null=True, verbose_name='Транскрипция (необязательно)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_audio_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аудио материал',
                'verbose_name_plural': 'Аудио материалы',
            },
        ),
        migrations.CreateModel(
            name='DocumentMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (необязательно)')),
                ('document_file', models.FileField(upload_to='material_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt', 'pptx', 'doc', 'docx'])], verbose_name='Файл документа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='ImageMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (необязательно)')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt текст (для доступности)')),
                ('image', models.ImageField(upload_to='material_images/', verbose_name='Файл изображения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_image_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название теста')),
                ('description', models.TextField(blank=True, verbose_name='Описание/Инструкция к тесту')),
                ('test_type', models.CharField(choices=[('mcq-multi', 'Выбор нескольких ответов'), ('mcq-single', 'Выбор одного ответа'), ('free-text', 'Текстовый ответ'), ('word-order', 'Правильный порядок слов'), ('matching', 'Соотнесение'), ('pronunciation', 'Проверка произношения'), ('spelling', 'Проверка правописания')], max_length=20, verbose_name='Тип теста')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attached_audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_using_audio', to='material_service.audiomaterial', verbose_name='Прикрепленное аудио')),
                ('attached_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_using_image', to='material_service.imagematerial', verbose_name='Прикрепленное изображение')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='SpellingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_spelling', models.TextField(blank=True, null=True, verbose_name='Эталонное написание (для сверки)')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Пояснение/Контекст к заданию')),
                ('test', models.OneToOneField(limit_choices_to={'test_type': 'spelling'}, on_delete=django.db.models.deletion.CASCADE, related_name='spelling_question', to='material_service.test', verbose_name='Тест на правописание')),
            ],
            options={
                'verbose_name': 'Вопрос на правописание',
                'verbose_name_plural': 'Вопросы на правописание',
            },
        ),
        migrations.CreateModel(
            name='PronunciationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_to_pronounce', models.TextField(blank=True, null=True, verbose_name='Текст для произношения (если есть)')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Пояснение/Контекст к заданию')),
                ('test', models.OneToOneField(limit_choices_to={'test_type': 'pronunciation'}, on_delete=django.db.models.deletion.CASCADE, related_name='pronunciation_question', to='material_service.test', verbose_name='Тест на произношение')),
            ],
            options={
                'verbose_name': 'Вопрос на произношение',
                'verbose_name_plural': 'Вопросы на произношение',
            },
        ),
        migrations.CreateModel(
            name='MCQOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст варианта ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ?')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Пояснение (если ответ неверный/верный)')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Общее пояснение к варианту (всегда видно после)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('test', models.ForeignKey(limit_choices_to={'test_type__in': ['mcq-single', 'mcq-multi']}, on_delete=django.db.models.deletion.CASCADE, related_name='mcq_options', to='material_service.test', verbose_name='Тест MCQ')),
            ],
            options={
                'verbose_name': 'Вариант ответа MCQ',
                'verbose_name_plural': 'Варианты ответов MCQ',
                'ordering': ['test', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Текст для соотнесения')),
                ('correct_answer_text', models.CharField(max_length=500, verbose_name="Текст правильного 'облачка'")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Пояснение к этой паре')),
                ('prompt_audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matching_prompts', to='material_service.audiomaterial', verbose_name='Аудио для соотнесения')),
                ('prompt_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matching_prompts', to='material_service.imagematerial', verbose_name='Изображение для соотнесения')),
                ('test', models.ForeignKey(limit_choices_to={'test_type': 'matching'}, on_delete=django.db.models.deletion.CASCADE, related_name='matching_pairs', to='material_service.test', verbose_name='Тест на соотнесение')),
            ],
            options={
                'verbose_name': 'Пара для соотнесения',
                'verbose_name_plural': 'Пары для соотнесения',
                'ordering': ['test', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MatchingDistractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distractor_text', models.CharField(max_length=500, verbose_name="Текст лишнего 'облачка'")),
                ('test', models.ForeignKey(limit_choices_to={'test_type': 'matching'}, on_delete=django.db.models.deletion.CASCADE, related_name='matching_distractors', to='material_service.test', verbose_name='Тест на соотнесение')),
            ],
            options={
                'verbose_name': 'Лишнее облачко (соотнесение)',
                'verbose_name_plural': 'Лишние облачка (соотнесение)',
            },
        ),
        migrations.CreateModel(
            name='FreeTextQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_answer', models.TextField(blank=True, null=True, verbose_name='Эталонный ответ (для сверки)')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Пояснение/Контекст к заданию')),
                ('test', models.OneToOneField(limit_choices_to={'test_type': 'free-text'}, on_delete=django.db.models.deletion.CASCADE, related_name='free_text_question', to='material_service.test', verbose_name='Тест с текстовым ответом')),
            ],
            options={
                'verbose_name': 'Вопрос с текстовым ответом',
                'verbose_name_plural': 'Вопросы с текстовым ответом',
            },
        ),
        migrations.CreateModel(
            name='TestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время отправки')),
                ('status', models.CharField(choices=[('submitted', 'Отправлено (ожидает автопроверки/отправки на проверку)'), ('grading_pending', 'На проверке'), ('graded', 'Проверено'), ('auto_failed', 'Автопроверка: Не пройдено'), ('auto_passed', 'Автопроверка: Пройдено')], default='submitted', max_length=20, verbose_name='Статус отправки')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Оценка (если применимо)')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Обратная связь от проверяющего')),
                ('section_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_submissions', to='lesson_service.sectionitem', verbose_name='Элемент раздела (контекст)')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='material_service.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Отправка теста',
                'verbose_name_plural': 'Отправки тестов',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SpellingSubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_image_file', models.ImageField(upload_to='submission_spelling/', verbose_name='Фото написания студента')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spelling_answer', to='material_service.testsubmission')),
            ],
            options={
                'verbose_name': 'Ответ на правописание',
                'verbose_name_plural': 'Ответы на правописание',
            },
        ),
        migrations.CreateModel(
            name='PronunciationSubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_audio_file', models.FileField(upload_to='submission_pronunciation/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])], verbose_name='Запись произношения студента')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciation_answer', to='material_service.testsubmission')),
            ],
            options={
                'verbose_name': 'Ответ на произношение',
                'verbose_name_plural': 'Ответы на произношение',
            },
        ),
        migrations.CreateModel(
            name='MCQSubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_options', models.ManyToManyField(related_name='submissions_selected_in', to='material_service.mcqoption', verbose_name='Выбранные варианты')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_answers', to='material_service.testsubmission')),
            ],
            options={
                'verbose_name': 'Ответ на MCQ',
                'verbose_name_plural': 'Ответы на MCQ',
            },
        ),
        migrations.CreateModel(
            name='FreeTextSubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Текст ответа студента')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='free_text_answer', to='material_service.testsubmission')),
            ],
            options={
                'verbose_name': 'Ответ текстом',
                'verbose_name_plural': 'Ответы текстом',
            },
        ),
        migrations.CreateModel(
            name='TextMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (необязательно)')),
                ('content', models.TextField(verbose_name='Содержимое (текст или Markdown)')),
                ('is_markdown', models.BooleanField(default=False, verbose_name='Использовать Markdown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_text_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Текстовый материал',
                'verbose_name_plural': 'Текстовые материалы',
            },
        ),
        migrations.CreateModel(
            name='VideoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (необязательно)')),
                ('source_type', models.CharField(choices=[('url', 'URL (YouTube, Vimeo, etc.)'), ('file', 'Загруженный файл')], default='url', max_length=10, verbose_name='Источник видео')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL видео (если источник URL)')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='material_video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'wmv'])], verbose_name='Видео файл (если источник файл)')),
                ('transcript', models.TextField(blank=True, null=True, verbose_name='Транскрипция (необязательно)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_video_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Видео материал',
                'verbose_name_plural': 'Видео материалы',
            },
        ),
        migrations.CreateModel(
            name='WordOrderSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_order_words', models.JSONField(default=list, verbose_name='Слова в правильном порядке')),
                ('distractor_words', models.JSONField(blank=True, default=list, verbose_name='Лишние слова (distractors)')),
                ('display_prompt', models.CharField(blank=True, max_length=500, verbose_name='Подсказка/Начало предложения (необязательно)')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Пояснение к этой паре')),
                ('test', models.OneToOneField(limit_choices_to={'test_type': 'word-order'}, on_delete=django.db.models.deletion.CASCADE, related_name='word_order_sentence', to='material_service.test', verbose_name='Тест на порядок слов')),
            ],
            options={
                'verbose_name': 'Предложение для теста на порядок слов',
                'verbose_name_plural': 'Предложения для тестов на порядок слов',
            },
        ),
        migrations.CreateModel(
            name='WordOrderSubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_order_words', models.JSONField(default=list, verbose_name='Отправленный порядок слов (JSON)')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='word_order_answer', to='material_service.testsubmission')),
            ],
            options={
                'verbose_name': 'Ответ на порядок слов',
                'verbose_name_plural': 'Ответы на порядок слов',
            },
        ),
        migrations.CreateModel(
            name='MatchingSubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_answer_text', models.CharField(max_length=500, verbose_name="Соотнесенное 'облачко' (ответ студента)")),
                ('matching_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_service.matchingpair', verbose_name='Пара (задание)')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_answers', to='material_service.testsubmission')),
            ],
            options={
                'verbose_name': 'Ответ на соотнесение',
                'verbose_name_plural': 'Ответы на соотнесение',
                'unique_together': {('submission', 'matching_pair')},
            },
        ),
    ]
