# Generated by Django 5.2 on 2025-05-18 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material_service", "0003_create_new_interactive_test_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchtarget",
            name="prompt_audio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="match_target_prompts",
                to="material_service.audiomaterial",
                verbose_name="Аудио-промпт цели",
            ),
        ),
        migrations.AlterField(
            model_name="matchtarget",
            name="prompt_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="match_target_prompts",
                to="material_service.imagematerial",
                verbose_name="Изображение-промпт цели",
            ),
        ),
    ]
