# Generated by Django 5.2 on 2025-05-20 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material_service", "0004_alter_matchtarget_prompt_audio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matchtarget",
            name="correct_item",
        ),
        migrations.RemoveField(
            model_name="dragtomatchsubmissionansweritem",
            name="dropped_item",
        ),
        migrations.RemoveField(
            model_name="sentenceorderslot",
            name="correct_item",
        ),
        migrations.AlterUniqueTogether(
            name="dragtomatchsubmissionansweritem",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="dragtomatchsubmissionansweritem",
            name="submission",
        ),
        migrations.RemoveField(
            model_name="dragtomatchsubmissionansweritem",
            name="target",
        ),
        migrations.RemoveField(
            model_name="matchtarget",
            name="prompt_audio",
        ),
        migrations.RemoveField(
            model_name="matchtarget",
            name="prompt_image",
        ),
        migrations.RemoveField(
            model_name="matchtarget",
            name="test",
        ),
        migrations.AlterUniqueTogether(
            name="sentenceorderslot",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="sentenceorderslot",
            name="test",
        ),
        migrations.RemoveField(
            model_name="sentenceordersubmissionanswer",
            name="submission",
        ),
        migrations.CreateModel(
            name="MatchingDistractor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distractor_text",
                    models.CharField(
                        max_length=500, verbose_name="Текст лишнего 'облачка'"
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        limit_choices_to={"test_type": "matching"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matching_distractors",
                        to="material_service.test",
                        verbose_name="Тест на соотнесение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лишнее облачко (соотнесение)",
                "verbose_name_plural": "Лишние облачка (соотнесение)",
            },
        ),
        migrations.CreateModel(
            name="MatchingPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt_text",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Текст для соотнесения",
                    ),
                ),
                (
                    "correct_answer_text",
                    models.CharField(
                        max_length=500, verbose_name="Текст правильного 'облачка'"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True, null=True, verbose_name="Пояснение к этой паре"
                    ),
                ),
                (
                    "prompt_audio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matching_prompts",
                        to="material_service.audiomaterial",
                        verbose_name="Аудио для соотнесения",
                    ),
                ),
                (
                    "prompt_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matching_prompts",
                        to="material_service.imagematerial",
                        verbose_name="Изображение для соотнесения",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        limit_choices_to={"test_type": "matching"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matching_pairs",
                        to="material_service.test",
                        verbose_name="Тест на соотнесение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пара для соотнесения",
                "verbose_name_plural": "Пары для соотнесения",
                "ordering": ["test", "order"],
            },
        ),
        migrations.CreateModel(
            name="MatchingSubmissionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submitted_answer_text",
                    models.CharField(
                        max_length=500,
                        verbose_name="Соотнесенное 'облачко' (ответ студента)",
                    ),
                ),
                (
                    "matching_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="material_service.matchingpair",
                        verbose_name="Пара (задание)",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matching_answers",
                        to="material_service.testsubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ на соотнесение",
                "verbose_name_plural": "Ответы на соотнесение",
                "unique_together": {("submission", "matching_pair")},
            },
        ),
        migrations.CreateModel(
            name="WordOrderSentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "correct_order_words",
                    models.JSONField(
                        default=list, verbose_name="Слова в правильном порядке"
                    ),
                ),
                (
                    "distractor_words",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Лишние слова (distractors)",
                    ),
                ),
                (
                    "display_prompt",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Подсказка/Начало предложения (необязательно)",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True, null=True, verbose_name="Пояснение к этой паре"
                    ),
                ),
                (
                    "test",
                    models.OneToOneField(
                        limit_choices_to={"test_type": "word-order"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_order_sentence",
                        to="material_service.test",
                        verbose_name="Тест на порядок слов",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предложение для теста на порядок слов",
                "verbose_name_plural": "Предложения для тестов на порядок слов",
            },
        ),
        migrations.CreateModel(
            name="WordOrderSubmissionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submitted_order_words",
                    models.JSONField(
                        default=list, verbose_name="Отправленный порядок слов (JSON)"
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_order_answer",
                        to="material_service.testsubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ на порядок слов",
                "verbose_name_plural": "Ответы на порядок слов",
            },
        ),
        migrations.DeleteModel(
            name="DraggableItem",
        ),
        migrations.DeleteModel(
            name="DragToMatchSubmissionAnswerItem",
        ),
        migrations.DeleteModel(
            name="MatchTarget",
        ),
        migrations.DeleteModel(
            name="SentenceOrderSlot",
        ),
        migrations.DeleteModel(
            name="SentenceOrderSubmissionAnswer",
        ),
    ]
