# Generated by Django 5.2 on 2025-05-20 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material_service", "0005_remove_matchtarget_correct_item_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="matchingpair",
            options={
                "ordering": ["test", "order"],
                "verbose_name": "Ячейка для перетаскивания (слот)",
                "verbose_name_plural": "Ячейки для перетаскивания (слоты)",
            },
        ),
        migrations.AlterModelOptions(
            name="wordordersentence",
            options={
                "verbose_name": "Задание на порядок слов (из пула)",
                "verbose_name_plural": "Задания на порядок слов (из пула)",
            },
        ),
        migrations.RemoveField(
            model_name="wordordersentence",
            name="correct_order_words",
        ),
        migrations.RemoveField(
            model_name="wordordersentence",
            name="distractor_words",
        ),
        migrations.AddField(
            model_name="test",
            name="draggable_options_pool",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Набор всех облачков (вариантов)"
            ),
        ),
        migrations.AddField(
            model_name="wordordersentence",
            name="correct_ordered_texts",
            field=models.JSONField(
                default=list,
                verbose_name="Тексты в правильном порядке (из пула облачков)",
            ),
        ),
        migrations.AlterField(
            model_name="matchingpair",
            name="correct_answer_text",
            field=models.CharField(
                max_length=500, verbose_name="Текст правильного облачка для этой ячейки"
            ),
        ),
        migrations.AlterField(
            model_name="matchingpair",
            name="explanation",
            field=models.TextField(
                blank=True, null=True, verbose_name="Пояснение к этой ячейке/ответу"
            ),
        ),
        migrations.AlterField(
            model_name="matchingpair",
            name="order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Порядок отображения ячейки"
            ),
        ),
        migrations.AlterField(
            model_name="matchingpair",
            name="prompt_audio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drag_drop_slot_audio",
                to="material_service.audiomaterial",
                verbose_name="Аудио-задание для ячейки",
            ),
        ),
        migrations.AlterField(
            model_name="matchingpair",
            name="prompt_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drag_drop_slot_images",
                to="material_service.imagematerial",
                verbose_name="Изображение-задание для ячейки",
            ),
        ),
        migrations.AlterField(
            model_name="matchingpair",
            name="prompt_text",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Текст-задание для ячейки (если есть)",
            ),
        ),
        migrations.AlterField(
            model_name="matchingpair",
            name="test",
            field=models.ForeignKey(
                limit_choices_to={"test_type": "drag-and-drop"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drag_drop_slots",
                to="material_service.test",
                verbose_name="Тест (Перетаскивание)",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="attached_audio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tests_using_audio",
                to="material_service.audiomaterial",
                verbose_name="Прикрепленное аудио к тесту (общее)",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="attached_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tests_using_image",
                to="material_service.imagematerial",
                verbose_name="Прикрепленное изображение к тесту (общее)",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="test_type",
            field=models.CharField(
                choices=[
                    ("mcq-multi", "Выбор нескольких ответов"),
                    ("mcq-single", "Выбор одного ответа"),
                    ("free-text", "Текстовый ответ"),
                    ("word-order", "Правильный порядок слов (в строке)"),
                    ("drag-and-drop", "Перетаскивание элементов (облачка и ячейки)"),
                    ("pronunciation", "Проверка произношения"),
                    ("spelling", "Проверка правописания"),
                ],
                max_length=20,
                verbose_name="Тип теста",
            ),
        ),
        migrations.AlterField(
            model_name="wordordersentence",
            name="explanation",
            field=models.TextField(
                blank=True, null=True, verbose_name="Пояснение к заданию"
            ),
        ),
        migrations.AlterField(
            model_name="wordordersentence",
            name="test",
            field=models.OneToOneField(
                limit_choices_to={"test_type": "word_order"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="word_order_sentence_details",
                to="material_service.test",
                verbose_name="Задание на порядок слов",
            ),
        ),
        migrations.CreateModel(
            name="DragDropSubmissionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dropped_option_text",
                    models.CharField(
                        max_length=500, verbose_name="Текст перетащенного облачка"
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Ответ правильный?"
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="material_service.matchingpair",
                        verbose_name="Ячейка (слот)",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drag_drop_answers",
                        to="material_service.testsubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ на перетаскивание в ячейку",
                "verbose_name_plural": "Ответы на перетаскивание в ячейки",
                "unique_together": {("submission", "slot")},
            },
        ),
        migrations.DeleteModel(
            name="MatchingDistractor",
        ),
    ]
