# Generated by Django 5.1.7 on 2025-07-24 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_service', '0006_alter_matchingpair_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqsubmissionanswer',
            name='selected_options',
            field=models.ManyToManyField(to='material_service.mcqoption', verbose_name='Выбранные варианты ответов'),
        ),
        migrations.AlterField(
            model_name='pronunciationsubmissionanswer',
            name='submitted_audio_file',
            field=models.FileField(upload_to='test_pronunciation_answers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])], verbose_name='Аудио ответ студента'),
        ),
        migrations.AlterField(
            model_name='spellingsubmissionanswer',
            name='submitted_image_file',
            field=models.ImageField(upload_to='test_spelling_answers/', verbose_name='Изображение с написанным ответом'),
        ),
    ]
