# Generated by Django 5.1.7 on 2026-01-20 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_service', '0007_alter_mcqsubmissionanswer_selected_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('mcq-multi', 'Выбор нескольких ответов'), ('mcq-single', 'Выбор одного ответа'), ('free-text', 'Текстовый ответ'), ('word-order', 'Правильный порядок слов (в строке)'), ('drag-and-drop', 'Перетаскивание элементов (облачка и ячейки)'), ('pronunciation', 'Проверка произношения'), ('spelling', 'Проверка правописания'), ('ai-conversation', 'AI Разговор (Кайва с сенсеем)')], max_length=20, verbose_name='Тип теста'),
        ),
        migrations.CreateModel(
            name='AiConversationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(verbose_name='Контекст разговора (О чём общаться)')),
                ('personality', models.TextField(blank=True, null=True, verbose_name='Личность/Характер модели (Опишите от себя)')),
                ('goodbye_condition', models.TextField(blank=True, null=True, verbose_name='Когда прощаться и заканчивать разговор (условие)')),
                ('background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_tests_using_background', to='material_service.imagematerial', verbose_name='Фон для разговора')),
                ('test', models.OneToOneField(limit_choices_to={'test_type': 'ai-conversation'}, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversation_question', to='material_service.test', verbose_name='Тест AI Разговор')),
            ],
            options={
                'verbose_name': 'Настройка AI разговора',
                'verbose_name_plural': 'Настройки AI разговоров',
            },
        ),
        migrations.CreateModel(
            name='AiConversationSubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.JSONField(default=list, verbose_name='История разговора (JSON)')),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Итоговая оценка (авто)')),
                ('evaluation_details', models.JSONField(default=dict, verbose_name='Детальная оценка (акцент, грамматика и т.д.)')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversation_answer', to='material_service.testsubmission', verbose_name='Отправка теста')),
            ],
            options={
                'verbose_name': 'Ответ на AI разговор',
                'verbose_name_plural': 'Ответы на AI разговоры',
            },
        ),
    ]
