# Generated by Django 5.1.7 on 2026-01-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict_service', '0001_initial'),
        ('material_service', '0008_alter_test_test_type_aiconversationquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversationquestion',
            name='dictionaries',
            field=models.ManyToManyField(blank=True, related_name='ai_conversation_questions', to='dict_service.dictionarysection', verbose_name='Словари для использования в разговоре'),
        ),
    ]
