# Generated by Django 5.1.7 on 2026-02-01 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_service', '0009_aiconversationquestion_dictionaries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordordersentence',
            name='test',
            field=models.OneToOneField(limit_choices_to={'test_type': 'word-order'}, on_delete=django.db.models.deletion.CASCADE, related_name='word_order_sentence_details', to='material_service.test', verbose_name='Задание на порядок слов'),
        ),
    ]
