# Generated by Django 5.1.7 on 2026-02-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_service', '0010_alter_wordordersentence_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversationquestion',
            name='assessment_criteria',
            field=models.TextField(blank=True, null=True, verbose_name='Критерии оценки (как ИИ должен оценивать ученика)'),
        ),
        migrations.AddField(
            model_name='aiconversationquestion',
            name='difficulty_level',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Уровень сложности (например, N5, Beginner)'),
        ),
        migrations.AddField(
            model_name='aiconversationquestion',
            name='key_vocabulary',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова/фразы (которые учитель хочет услышать)'),
        ),
        migrations.AddField(
            model_name='aiconversationquestion',
            name='speaking_style',
            field=models.TextField(blank=True, null=True, verbose_name='Стиль речи (например, формальный, вежливый, сленг)'),
        ),
    ]
