# Generated by Django 5.1.7 on 2026-02-26 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_service', '0011_aiconversationquestion_assessment_criteria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('mcq-multi', 'Выбор нескольких ответов'), ('mcq-single', 'Выбор одного ответа'), ('free-text', 'Текстовый ответ'), ('word-order', 'Правильный порядок слов (в строке)'), ('drag-and-drop', 'Перетаскивание элементов (облачка и ячейки)'), ('pronunciation', 'Проверка произношения'), ('spelling', 'Проверка правописания'), ('ai-conversation', 'AI Разговор (Кайва с сенсеем)'), ('kanji-tracing', 'Прописи (иероглифы)')], max_length=20, verbose_name='Тип теста'),
        ),
        migrations.CreateModel(
            name='KanjiTracingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.CharField(blank=True, max_length=10, null=True, verbose_name='Кандзи/Кана (если из базы)')),
                ('custom_image', models.ImageField(blank=True, null=True, upload_to='kanji_tracing_custom/', verbose_name='Своё фото кандзи')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки/Чтение (длинное поле справа)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок прописи')),
                ('test', models.ForeignKey(limit_choices_to={'test_type': 'kanji-tracing'}, on_delete=django.db.models.deletion.CASCADE, related_name='kanji_tracing_items', to='material_service.test', verbose_name='Тест (Прописи)')),
            ],
            options={
                'verbose_name': 'Элемент прописи',
                'verbose_name_plural': 'Элементы прописей',
                'ordering': ['test', 'order'],
            },
        ),
        migrations.CreateModel(
            name='KanjiTracingSubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_image_file', models.ImageField(blank=True, null=True, upload_to='test_kanji_tracing_answers/', verbose_name='Изображение заполненной прописи')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kanji_tracing_answer', to='material_service.testsubmission')),
            ],
            options={
                'verbose_name': 'Ответ на прописи',
                'verbose_name_plural': 'Ответы на прописи',
            },
        ),
    ]
