# Generated by Django 5.1.7 on 2026-03-08 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_service', '0012_alter_test_test_type_kanjitracingitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronunciationquestion',
            name='reference_audio_file',
            field=models.FileField(blank=True, null=True, upload_to='test_pronunciation_references/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])], verbose_name='Эталонное аудио (от преподавателя)'),
        ),
        migrations.AddField(
            model_name='pronunciationquestion',
            name='transcript',
            field=models.TextField(blank=True, null=True, verbose_name='Транскрипция речи'),
        ),
        migrations.AddField(
            model_name='pronunciationsubmissionanswer',
            name='result_graph',
            field=models.ImageField(blank=True, null=True, upload_to='test_pronunciation_graphs/', verbose_name='График сравнения (от Onsei API)'),
        ),
    ]
