# Generated by Django 5.1.7 on 2026-03-08 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_service', '0014_remove_pronunciationsubmissionanswer_result_graph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pronunciationquestion',
            name='reference_audio_file',
            field=models.FileField(blank=True, null=True, upload_to='test_pronunciation_references/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a', 'webm'])], verbose_name='Эталонное аудио (от преподавателя)'),
        ),
        migrations.AlterField(
            model_name='pronunciationquestion',
            name='transcript',
            field=models.TextField(default='', verbose_name='Транскрипция речи'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pronunciationsubmissionanswer',
            name='submitted_audio_file',
            field=models.FileField(upload_to='test_pronunciation_answers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a', 'webm'])], verbose_name='Аудио ответ студента'),
        ),
    ]
