# Generated by Django 5.1.7 on 2026-03-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_service', '0015_alter_pronunciationquestion_reference_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiomaterial',
            name='source',
            field=models.TextField(blank=True, default='', verbose_name='Источник (необязательно)'),
        ),
        migrations.AddField(
            model_name='documentmaterial',
            name='source',
            field=models.TextField(blank=True, default='', verbose_name='Источник (необязательно)'),
        ),
        migrations.AddField(
            model_name='imagematerial',
            name='source',
            field=models.TextField(blank=True, default='', verbose_name='Источник (необязательно)'),
        ),
        migrations.AddField(
            model_name='test',
            name='source',
            field=models.TextField(blank=True, default='', verbose_name='Источник (необязательно)'),
        ),
        migrations.AddField(
            model_name='textmaterial',
            name='source',
            field=models.TextField(blank=True, default='', verbose_name='Источник (необязательно)'),
        ),
        migrations.AddField(
            model_name='videomaterial',
            name='source',
            field=models.TextField(blank=True, default='', verbose_name='Источник (необязательно)'),
        ),
    ]
