# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recognition.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11recognition.proto\x12\x0brecognition"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02"O\n\x0b\x42oundingBox\x12\x1f\n\x03min\x18\x01 \x01(\x0b\x32\x12.recognition.Point\x12\x1f\n\x03max\x18\x02 \x01(\x0b\x32\x12.recognition.Point"6\n\x10NormalizedStroke\x12\"\n\x06points\x18\x01 \x03(\x0b\x32\x12.recognition.Point"\xc6\x01\n\x0eStrokeFeatures\x12.\n\x0c\x62ounding_box\x18\x01 \x01(\x0b\x32\x18.recognition.BoundingBox\x12\'\n\x0bstart_point\x18\x02 \x01(\x0b\x32\x12.recognition.Point\x12%\n\tend_point\x18\x03 \x01(\x0b\x32\x12.recognition.Point\x12$\n\x08\x63\x65ntroid\x18\x04 \x01(\x0b\x32\x12.recognition.Point\x12\x0e\n\x06length\x18\x05 \x01(\x02"\xf8\x01\n\x12RecognitionRequest\x12\x39\n\x12normalized_strokes\x18\x01 \x03(\x0b\x32\x1d.recognition.NormalizedStroke\x12\x34\n\x0fstroke_features\x18\x02 \x03(\x0b\x32\x1b.recognition.StrokeFeatures\x12\x35\n\x13global_bounding_box\x18\x03 \x01(\x0b\x32\x18.recognition.BoundingBox\x12+\n\x0fglobal_centroid\x18\x04 \x01(\x0b\x32\x12.recognition.Point\x12\r\n\x05top_n\x18\x05 \x01(\x05"L\n\x11RecognitionResult\x12\x11\n\tcharacter\x18\x01 \x01(\t\x12\x10\n\x08\x64istance\x18\x02 \x01(\x02\x12\x12\n\nconfidence\x18\x03 \x01(\x02"F\n\x13RecognitionResponse\x12/\n\x07results\x18\x01 \x03(\x0b\x32\x1e.recognition.RecognitionResult2f\n\x12RecognitionService\x12P\n\tRecognize\x12\x1f.recognition.RecognitionRequest\x1a .recognition.RecognitionResponse"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dict_service.recognition_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POINT._serialized_start=34
  _POINT._serialized_end=63
  _BOUNDINGBOX._serialized_start=65
  _BOUNDINGBOX._serialized_end=144
  _NORMALIZEDSTROKE._serialized_start=146
  _NORMALIZEDSTROKE._serialized_end=200
  _STROKEFEATURES._serialized_start=203
  _STROKEFEATURES._serialized_end=401
  _RECOGNITIONREQUEST._serialized_start=404
  _RECOGNITIONREQUEST._serialized_end=652
  _RECOGNITIONRESULT._serialized_start=654
  _RECOGNITIONRESULT._serialized_end=730
  _RECOGNITIONRESPONSE._serialized_start=732
  _RECOGNITIONRESPONSE._serialized_end=802
  _RECOGNITIONSERVICE._serialized_start=804
  _RECOGNITIONSERVICE._serialized_end=906
# @@protoc_insertion_point(module_scope)
