# Generated by Django 5.1.7 on 2026-03-31 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_service', '0006_alter_course_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Дата по МСК', verbose_name='Дата испытания')),
                ('generation_status', models.CharField(choices=[('pending', 'Ожидает генерации'), ('generating', 'Генерируется'), ('ready', 'Готово'), ('failed', 'Ошибка генерации')], default='pending', max_length=20, verbose_name='Статус генерации')),
                ('completion_status', models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В процессе'), ('completed', 'Завершено')], default='not_started', max_length=20, verbose_name='Статус прохождения')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255, verbose_name='ID Celery-задачи')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Набранные очки')),
                ('total_items', models.PositiveIntegerField(default=0, verbose_name='Всего заданий')),
                ('correct_items', models.PositiveIntegerField(default=0, verbose_name='Правильных ответов')),
                ('coins_awarded', models.PositiveIntegerField(default=0, verbose_name='Начислено монет')),
                ('media_placeholders', models.JSONField(blank=True, default=list, help_text='Промпты для генерации картинок/аудио. Заполняются нейронкой.', verbose_name='Слоты для медиа (будущая генерация)')),
                ('blitz_quizzes', models.JSONField(blank=True, default=list, verbose_name='Блиц-тесты (JSON)')),
                ('generation_error', models.TextField(blank=True, default='', verbose_name='Ошибка генерации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenges', to='course_service.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenges', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Ежедневное испытание',
                'verbose_name_plural': 'Ежедневные испытания',
                'ordering': ['-date'],
                'unique_together': {('user', 'course', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ChallengeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('item_type', models.CharField(choices=[('mcq-single', 'Выбор одного ответа'), ('mcq-multi', 'Выбор нескольких ответов'), ('word-order', 'Правильный порядок слов'), ('drag-and-drop', 'Перетаскивание'), ('free-text', 'Текстовый ответ')], max_length=20, verbose_name='Тип теста')),
                ('question_data', models.JSONField(default=dict, help_text='Вопрос, варианты ответов, правильный ответ и т.д.', verbose_name='Данные вопроса (JSON)')),
                ('media_slots', models.JSONField(blank=True, default=list, help_text='Промпты для генерации картинок/аудио к этому тесту', null=True, verbose_name='Слоты для медиа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='challenge_service.dailychallenge', verbose_name='Испытание')),
            ],
            options={
                'verbose_name': 'Задание испытания',
                'verbose_name_plural': 'Задания испытаний',
                'ordering': ['challenge', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_data', models.JSONField(default=dict, verbose_name='Данные ответа (JSON)')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Правильный ответ?')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Время ответа')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='challenge_service.challengeitem', verbose_name='Задание')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='challenge_service.dailychallenge', verbose_name='Испытание')),
            ],
            options={
                'verbose_name': 'Ответ на задание',
                'verbose_name_plural': 'Ответы на задания',
                'unique_together': {('challenge', 'item')},
            },
        ),
        migrations.CreateModel(
            name='UserKnowledgeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_data', models.JSONField(default=dict, help_text='Сильные/слабые стороны, темы для повторения, рекомендации', verbose_name='Данные профиля (JSON)')),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний анализ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_profiles', to='course_service.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Профиль знаний',
                'verbose_name_plural': 'Профили знаний',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
