# Generated by Django 5.1.7 on 2026-03-31 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_service', '0001_initial'),
        ('material_service', '0016_audiomaterial_source_documentmaterial_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengeitem',
            name='challenge',
        ),
        migrations.CreateModel(
            name='ChallengeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_tests', to='challenge_service.dailychallenge', verbose_name='Испытание')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_links', to='material_service.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Тест испытания',
                'verbose_name_plural': 'Тесты испытаний',
                'ordering': ['challenge', 'order'],
                'unique_together': {('challenge', 'test')},
            },
        ),
        migrations.DeleteModel(
            name='ChallengeAnswer',
        ),
        migrations.DeleteModel(
            name='ChallengeItem',
        ),
    ]
