# Generated by Django 5.1.7 on 2026-03-16 19:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_service', '0006_alter_course_status'),
        ('material_service', '0015_alter_pronunciationquestion_reference_audio_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название экзамена')),
                ('description', models.TextField(blank=True, verbose_name='Описание / Инструкция')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Сколько минут даётся на прохождение экзамена', verbose_name='Длительность (минуты)')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('require_camera', models.BooleanField(default=True, verbose_name='Требуется камера (прокторинг)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='course_service.course', verbose_name='Курс')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'Экзамены',
                'ordering': ['course', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершён'), ('timed_out', 'Время истекло'), ('terminated_by_proctoring', 'Прекращён (прокторинг)')], default='in_progress', max_length=30, verbose_name='Статус')),
                ('current_section_order', models.PositiveIntegerField(default=0, verbose_name='Текущая секция (order)')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начато')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Итоговый балл')),
                ('max_possible_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимально возможный балл')),
                ('camera_violation_seconds', models.FloatField(default=0, verbose_name='Время нарушений камеры (сек)')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exam_service.exam', verbose_name='Экзамен')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Попытка экзамена',
                'verbose_name_plural': 'Попытки экзаменов',
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ExamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название секции')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='exam_service.exam', verbose_name='Экзамен')),
            ],
            options={
                'verbose_name': 'Секция экзамена',
                'verbose_name_plural': 'Секции экзамена',
                'ordering': ['exam', 'order'],
                'unique_together': {('exam', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ExamSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='exam_service.examsection', verbose_name='Секция')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_items', to='material_service.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Элемент секции экзамена',
                'verbose_name_plural': 'Элементы секций экзамена',
                'ordering': ['section', 'order'],
                'unique_together': {('section', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_data', models.JSONField(default=dict, help_text='Формат зависит от типа теста', verbose_name='Данные ответа (JSON)')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Балл')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Правильно?')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam_service.examattempt', verbose_name='Попытка')),
                ('exam_section_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_service.examsectionitem', verbose_name='Элемент секции')),
            ],
            options={
                'verbose_name': 'Ответ на экзамене',
                'verbose_name_plural': 'Ответы на экзамене',
                'unique_together': {('attempt', 'exam_section_item')},
            },
        ),
    ]
