# Generated by Django 5.1.7 on 2026-03-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examanswer',
            name='submitted_file',
            field=models.FileField(blank=True, null=True, upload_to='exam_answers/', verbose_name='Прикрепленный файл'),
        ),
    ]
