# Generated by Django 5.1.7 on 2026-03-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_service', '0002_examanswer_submitted_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examattempt',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='exam',
            name='passing_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Проходной балл'),
        ),
        migrations.AddField(
            model_name='exam',
            name='retake_interval_minutes',
            field=models.PositiveIntegerField(default=0, help_text='0 — без ограничений по времени.', verbose_name='Интервал между попытками (минуты)'),
        ),
        migrations.AddField(
            model_name='examsectionitem',
            name='custom_max_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Если пусто, используется дефолтный балл (обычно 1.0)', max_digits=5, null=True, verbose_name='Кастомный максимальный балл'),
        ),
    ]
