# Generated by Django 5.2 on 2025-08-12 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course_service", "0005_alter_course_status"),
        ("lesson_service", "0004_alter_sectionitem_content_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_study_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего дней обучения"
                    ),
                ),
                (
                    "current_streak_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Текущая серия дней"
                    ),
                ),
                (
                    "longest_streak_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Самая длинная серия дней"
                    ),
                ),
                (
                    "average_daily_time_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Среднее время в день (минуты)"
                    ),
                ),
                (
                    "total_achievements",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего достижений"
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(default=1, verbose_name="Уровень"),
                ),
                (
                    "experience_points",
                    models.PositiveIntegerField(default=0, verbose_name="Очки опыта"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_stats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статистика обучения",
                "verbose_name_plural": "Статистика обучения",
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_courses_enrolled",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего записей на курсы"
                    ),
                ),
                (
                    "total_courses_completed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего завершенных курсов"
                    ),
                ),
                (
                    "total_lessons_completed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего завершенных уроков"
                    ),
                ),
                (
                    "total_sections_completed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего завершенных разделов"
                    ),
                ),
                (
                    "total_tests_passed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего пройденных тестов"
                    ),
                ),
                (
                    "total_tests_failed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего проваленных тестов"
                    ),
                ),
                (
                    "total_learning_time_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Общее время обучения (минуты)"
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последняя активность"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс пользователя",
                "verbose_name_plural": "Прогресс пользователей",
            },
        ),
        migrations.CreateModel(
            name="CourseProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_lessons",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего уроков в курсе"
                    ),
                ),
                (
                    "completed_lessons",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Завершенных уроков"
                    ),
                ),
                (
                    "total_sections",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего разделов в курсе"
                    ),
                ),
                (
                    "completed_sections",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Завершенных разделов"
                    ),
                ),
                (
                    "total_tests",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего тестов в курсе"
                    ),
                ),
                (
                    "passed_tests",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Пройденных тестов"
                    ),
                ),
                (
                    "failed_tests",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Проваленных тестов"
                    ),
                ),
                (
                    "completion_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Процент завершения",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата начала"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последняя активность"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="course_service.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс по курсу",
                "verbose_name_plural": "Прогресс по курсам",
                "unique_together": {("user", "course")},
            },
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_sections",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего разделов в уроке"
                    ),
                ),
                (
                    "completed_sections",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Завершенных разделов"
                    ),
                ),
                (
                    "total_tests",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего тестов в уроке"
                    ),
                ),
                (
                    "passed_tests",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Пройденных тестов"
                    ),
                ),
                (
                    "failed_tests",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Проваленных тестов"
                    ),
                ),
                (
                    "completion_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Процент завершения",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата начала"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последняя активность"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="lesson_service.lesson",
                        verbose_name="Урок",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс по уроку",
                "verbose_name_plural": "Прогресс по урокам",
                "unique_together": {("user", "lesson")},
            },
        ),
        migrations.CreateModel(
            name="TestProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_id", models.PositiveIntegerField(verbose_name="ID теста")),
                (
                    "test_title",
                    models.CharField(max_length=255, verbose_name="Название теста"),
                ),
                (
                    "test_type",
                    models.CharField(max_length=50, verbose_name="Тип теста"),
                ),
                ("section_id", models.PositiveIntegerField(verbose_name="ID раздела")),
                ("lesson_id", models.PositiveIntegerField(verbose_name="ID урока")),
                ("course_id", models.PositiveIntegerField(verbose_name="ID курса")),
                (
                    "attempts_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество попыток"
                    ),
                ),
                (
                    "best_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Лучший результат",
                    ),
                ),
                (
                    "last_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Последний результат",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Не начат"),
                            ("in_progress", "В процессе"),
                            ("passed", "Пройден"),
                            ("failed", "Провален"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "first_attempt_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Первая попытка"
                    ),
                ),
                (
                    "last_attempt_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последняя попытка"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс по тесту",
                "verbose_name_plural": "Прогресс по тестам",
                "unique_together": {("user", "test_id")},
            },
        ),
    ]
