# Generated by Django 5.2 on 2025-08-13 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesson_service", "0004_alter_sectionitem_content_type"),
        ("progress_service", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_items",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего элементов в секции"
                    ),
                ),
                (
                    "completed_items",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Завершенных элементов"
                    ),
                ),
                (
                    "total_tests",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего тестов в секции"
                    ),
                ),
                (
                    "passed_tests",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Пройденных тестов"
                    ),
                ),
                (
                    "failed_tests",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Проваленных тестов"
                    ),
                ),
                (
                    "completion_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Процент завершения",
                    ),
                ),
                (
                    "is_visited",
                    models.BooleanField(default=False, verbose_name="Посещена"),
                ),
                (
                    "visited_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата посещения"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата начала"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последняя активность"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="lesson_service.section",
                        verbose_name="Секция",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс по секции",
                "verbose_name_plural": "Прогресс по секциям",
                "unique_together": {("user", "section")},
            },
        ),
    ]
