# Generated by Django 5.1.7 on 2025-08-13 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_service', '0002_sectionprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionItemView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.PositiveIntegerField(verbose_name='ID раздела')),
                ('section_item_id', models.PositiveIntegerField(verbose_name='ID элемента раздела')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата первого просмотра')),
                ('last_viewed_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего просмотра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_item_views', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Просмотр элемента раздела',
                'verbose_name_plural': 'Просмотры элементов раздела',
                'unique_together': {('user', 'section_item_id')},
            },
        ),
    ]
