# Generated by Django 5.1.7 on 2025-11-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_service', '0003_sectionitemview'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningstats',
            name='coins',
            field=models.PositiveIntegerField(default=0, verbose_name='Монеты (тратятся)'),
        ),
        migrations.AlterField(
            model_name='learningstats',
            name='experience_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Очки опыта (накапливаются)'),
        ),
    ]
