# Generated by Django 5.1.7 on 2026-02-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='frame_image',
            field=models.FileField(blank=True, null=True, upload_to='avatar_frames/'),
        ),
    ]
