# Generated by Django 5.2 on 2025-11-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievement_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="achievements/icons/",
                verbose_name="Иконка",
            ),
        ),
    ]
