# Generated by Django 5.2 on 2025-11-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievement_service", "0002_alter_achievement_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="triggers",
            field=models.JSONField(blank=True, default=list, verbose_name="Триггеры"),
        ),
    ]
