# Generated by Django 5.2 on 2025-04-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='subtitle',
        ),
    ]
