# Generated by Django 5.2 on 2025-04-17 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('lesson_service', '0002_remove_lesson_description_remove_lesson_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения элемента в разделе', verbose_name='Порядок в разделе')),
                ('item_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('audio', 'Аудио'), ('video', 'Видео'), ('document', 'Документ/Презентация'), ('test', 'Тест')], max_length=20, verbose_name='Тип элемента')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта контента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контента')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lesson_service.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Элемент раздела',
                'verbose_name_plural': 'Элементы разделов',
                'ordering': ['section', 'order'],
                'unique_together': {('section', 'order')},
            },
        ),
    ]
