# Generated by Django 5.2 on 2025-04-17 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('lesson_service', '0003_sectionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionitem',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label': 'material_service'}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контента'),
        ),
    ]
