# Generated by Django 5.1.7 on 2026-02-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_service', '0005_alter_lesson_options_lesson_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='table_of_contents',
            field=models.TextField(blank=True, help_text='Опциональное оглавление или краткое описание содержания урока', null=True, verbose_name='Оглавление'),
        ),
    ]
